<html>
<head>
<STYLE TYPE="text/css"><!--
A:link {color: lightred; text-decoration:none; font}
A:visited {color: lightred; text-decoration:none; font}
A:active {text-decoration:none; color=#ff0000}
A:hover {text-decoration: underline; font}
--></STYLE>
</head>
<body background="im/ugolok-fon.gif" bgcolor=#fffffe text=#000000 link=#006600>
<centeR>
<a target=_top href="http://www.aec.neva.ru/internet-school/"><img src=im/address2.gif border=0 width=255 heighT=16></a>
<table width=100% cellspacing="0" cellpadding="0" border=0 bgcolor=#ffffff>
<tr>
<td windth=13><img src=im/ugolok1.gif width=13 height=13></td>
<td windth=99%><img src=im/blanck.gif width=554 height=13></td>
<td windth=13 align=right><img src=im/ugolok2.gif width=13 height=13></td>
</tr><tr>
<td windth=13><img src=im/blanck.gif width=1 height=13></td>
<td windth=99% align=center>
<font size=+2><b>

ОТПРАВКА АНКЕТЫ НА СЕРВЕР<br>
(прием на курсы дистанционного дополнительного обучения по математике)


</b></font>
</td>
<td windth=13><img src=im/blanck.gif width=1 height=13></td>
</tr><tr>
<td windth=13><img src=im/ugolok4.gif width=13 height=13></td>
<td windth=99%><img src=im/blanck.gif width=1 height=13></td>
<td windth=13 align=right><img src=im/ugolok3.gif width=13 height=13></td>
</tr></table>
</center>
<br>







<centeR>
<table width=100% cellspacing="0" cellpadding="0" border=0 bgcolor=#ffffff>
<tr>
<td windth=13><img src=im/ugolok1.gif width=13 height=13></td>
<td windth=99%><img src=im/blanck.gif width=554 height=13></td>
<td windth=13 align=right><img src=im/ugolok2.gif width=13 height=13></td>
</tr><tr>
<td windth=13><img src=im/blanck.gif width=1 height=13></td>
<td windth=99%><br>

<p>&nbsp;&nbsp;&nbsp;
"Петербургская Интернет-школа" приглашает учащихся 7-11 классов, имеющих домашний компьютер и среду Windows на нем, на дистанционные курсы дополнительного обучения по математике. Цель курсов - развитие умений самостоятельного решения задач по алгебре и анализу. 

<p>&nbsp;&nbsp;&nbsp;
Желающие обучаться (абитуриенты) 
<ul>
        <li> заполняют анкету и оплачивают входное тестирование знаний; после этого по электронной почте им высылается тестовая работа;
        <li> выполнив работу, абитуриенты отсылают файл результатов в школу; на основании результатов уточняется тематика индивидуальных занятий;
        <li> далее ежемесячно ученик получает индивидуальные интерактивные задачники (работающие в среде Verifier, которая передается ученику вместе с входным тестом);
        <li> в течение трех недель ученик работает с интерактивным задачником, после чего отсылает файлы с протоколами работы (генерируются автоматически) в школу. 
</ul>

<p>&nbsp;&nbsp;&nbsp;
Стоимость обучения в школе - 3$ в месяц + 3$ входное тестирование. Срок обучения предлагается школой на основании теста. Набор в школу осуществляется непрерывно.
<p>&nbsp;&nbsp;&nbsp;
<b>Анкета:</b>
<ul>
        <li> ФИО
        <li> Адрес электронной почты
        <li> Домашний почтовый адрес
        <li> Школа, класс
        <li> Краткое описание пожеланий или проблем, связанных с изучением математики
        <li> Модель домашнего компьютера и тип операционной среды на нем
</ul>

<p>&nbsp;&nbsp;&nbsp;
Деньги за тестирование следует перевести на счет школы через отделение Сбербанка или выслать почтовым переводом. 

<b>Реквизиты:</b><br>
<pre>Наименование получателя платежа:
        ИНН 7808029878; 
        ЦПО "Информатизация образования"
        р/с 40703810500000000062
        в ОАО "Витабанк"
        к/с 30101810900000000758
        БИК 044030758
</pre>

<b>Адрес:</b><br>
191025, Санкт-Петербург, ул. Марата, д. 25<br>
ЦПО "Информатизация образования"<br>
Петербургская Интернет-школа, <br>
исполнительному директору Суворовой О.А.
<p>
(За справками обращаться по электронной почте: <a href="mailto:pozdnkov@aec.neva.ru">pozdnkov@aec.neva.ru</a>)



<br>&nbsp;</td>
<td windth=13><img src=im/blanck.gif width=1 height=13></td>
</tr><tr>
<td windth=13><img src=im/ugolok4.gif width=13 height=13></td>
<td windth=99%><img src=im/blanck.gif width=1 height=13></td>
<td windth=13 align=right><img src=im/ugolok3.gif width=13 height=13></td>
</tr></table>
<a target=_top href="http://www.aec.neva.ru/center/"><img src=im/address.gif border=0 width=135 heighT=18></a>
</center>





</body></html>