<?

$mailto="sergey@ipo.spb.ru";
//$mailto="del@aec.neva.ru";

$subject[]="ошибочное письмо";
$subject[]="Второй конкурс проектов методических материалов для дистанционного обучения \"Петербургская Интернет-школа\" ( http://www.aec.neva.ru/internet-school/ch2-1.htm )";
$subject[]="Международный заочный математический кружок - АНКЕТА ( http://www.aec.neva.ru/internet-school/a/fedotov/5.htm )";

      if ($nomer<0 || $nomer>count($subject)) { echo "error"; exit; }

      $z="*****[".(date("H:i:s d/m/Y",time()))."]*****\n
ТИП ПИСЬМА - [".$subject[intval($nomer)]."]\n";
      $z=$z."Заказ от ".getenv("REMOTE_ADDR")." (".getenv("REMOTE_HOST").")\n";

      for ($i=0; $i<count($text) && $i<10; $i++) {
 
         $z=$z."*** ".substr($info[$i],0,100)."\n".substr($text[$i],0,300)."\n\n";

      }

      mail($mailto, "INTERNET-SCHOOL", $z,
        "From: \"WWW script, DO NOT REPLAY\" <$mailto>\n".
        "BCC: del@aec.neva.ru\n".
        "CC: vphedotov@mail.ru\n".
        "MIME-Version: 1.0\n".
        "Content-Type: text/plain; charset=Windows-1251\n".
        "Content-Transfer-Encoding: 8bit");

      Echo "<html><head>
     <META HTTP-EQUIV='Refresh' CONTENT='5;url=$url'>
      </heaD><body><center><h3>Ваше сообщение отправлено!</h3></center><p>
      <a href='$url'>Назад, на страницу заполнения формы</a> (вы <b>автоматически</b> туда перейдете через 5 сек)";



?>
