<html>
<head>
<STYLE TYPE="text/css"><!--
A:link {color: lightred; text-decoration:none; font}
A:visited {color: lightred; text-decoration:none; font}
A:active {text-decoration:none; color=#ff0000}
A:hover {text-decoration: underline; font}
--></STYLE>
</head>

<body background="../../im/ugolok-fon.gif" bgcolor=#fffffe text=#003300 link=#000066 vlink=#660000>
<centeR>
<a target=_top href="http://www.aec.neva.ru/internet-school/"><img src=../../im/address2.gif border=0 width=255 heighT=16></a>
<table width=100% cellspacing="0" cellpadding="0" border=0 bgcolor=#ffffff>
<tr>
<td windth=13><img src=../../im/ugolok1.gif width=13 height=13></td>
<td windth=99%><img src=../../im/blanck.gif width=554 height=13></td>
<td windth=13 align=right><img src=../../im/ugolok2.gif width=13 height=13></td>
</tr><tr>
<td windth=13><img src=../../im/blanck.gif width=1 height=13></td>
<td windth=99% align=center>
<b>
Заочная Школа Современного Программирования
<font size=+2>
<br>Доска почета
</font>
</b></font>
</td>
<td windth=13><img src=../../im/blanck.gif width=1 height=13></td>
</tr><tr>
<td windth=13><img src=../../im/ugolok4.gif width=13 height=13></td>
<td windth=99%><img src=../../im/blanck.gif width=1 height=13></td>
<td windth=13 align=right><img src=../../im/ugolok3.gif width=13 height=13></td>
</tr></table>
</center>
<br>

<centeR>
<table width=100% cellspacing="0" cellpadding="0" border=0 bgcolor=#ffffff>
<tr>
<td windth=13><img src=../../im/ugolok1.gif width=13 height=13></td>
<td windth=99%><img src=../../im/blanck.gif width=554 height=13></td>
<td windth=13 align=right><img src=../../im/ugolok2.gif width=13 height=13></td>
</tr><tr>
<td windth=13><img src=../../im/blanck.gif width=1 height=13></td>
<td windth=99%><br>

<?
  include "photo.html";
?>

<hr>
Для участия в проекте присылайте Ваше фото и резюме на 
<a href="school@ipo.spb.ru">school@ipo.spb.ru</a>


<br>&nbsp;</td>
<td windth=13><img src=../../im/blanck.gif width=1 height=13></td>
</tr><tr>
<td windth=13><img src=../../im/ugolok4.gif width=13 height=13></td>
<td windth=99%><img src=../../im/blanck.gif width=1 height=13></td>
<td windth=13 align=right><img src=../../im/ugolok3.gif width=13 height=13></td>
</tr></table>
<a target=_top href="http://www.aec.neva.ru/center/"><img src=../../im/address.gif border=0 width=135 heighT=18></a>
</center>


</body></html>



