<? include("_start.htm") ?>

<center>
<table cellspacing=0 cellpadding=0 border=0><tr>
<td width=><img src=../im/ch4b.gif border=0 width=143 heighT=135></td>
<td><img src=../im/blanck.gif width=5 height=1></td>
<td><img src=../im/ch4.gif width=390 height=59></td></tr>
</table>
</center>

<? include("_middle.htm") ?>

<table border=0>

<tr><td colspan=3><b><font color=#006600>
<b><font color=#006600>
&nbsp;<br>
Диcтанционное обучение в школе:
</font></b><br></td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="ch4-1.htm">Как поступить в Школу Современного Программирования</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="naputst.htm">Напутствие учащимся пpоф. И.В.Романовского</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="pamjat.htm">Памятка учащемуся (рекомендации и требования к присылаемым задачам)</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="zaoch.htm">Заочная школа современного программирования в 2000-м году</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="newcurs.htm">Новый курс заочной школы</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="student.htm">Страничка ученика Заочной Школы</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="progr/index.phtml">Интересное для программистов (дополнительные материалы)</td></tr>

<tr><td colspan=3><b><font color=#006600>
<a name="vuz"></a>
<b><font color=#006600>
&nbsp;<br>
Диcтанционное обучение в ВУЗе:
</font></b><br></td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
Система автоматизированного решения задач (М.Дмитpиева и М.Павлова). Вы можете загрузить эту программу - 
<a href="../ch5.htm#solver2">SOLVER2.RAR</a>:</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/blanck.gif width=12 height=12></td><td width=557>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;<a href="25-1.htm">часть [1]</A><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;<a href="25-2.htm">часть [2]</A><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;<a href="25-3.htm">часть [3]</a></td></tr>
<!--
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="a/30.htm">Материалы к лекциям по построению и анализу алгоритмов</a> (перевод с английского, автор Д.Эпштейн)</td></tr>
-->
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="ch4-3.htm">Индивидуальные задания по математической логике и теории алгоритмов</a> (С.Н.Поздняков)</td></tr>

<tr><td colspan=3><b><font color=#006600>
<br>
Статьи:
</font></b><br></td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="20.htm">Подготовка компьютерщиков - профессионалов </a> (В.Паpфенов)</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="21.htm">X Всероссийская олимпиада школьников по информатике</a> (И.Миpонов)</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="22.htm">Командные соревнования школьников по программированию</a> (И.Миpонов)</br>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="23.htm">Кружки и олимпиады по программированию</a> (П.Чеpкасова)</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="24.htm">Элементы теории множеств; Система: ее структура и состояние</a> (М.Дмитpиева и М.Павлова)</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="26.htm">Задача о складывании марок</a> (В.Костин)</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="27.htm">Изучение логического программирования</a> (И.Соловьев)</td></tr>
<tr><td width=15>&nbsp;</td><td width=12><img src=../im/ball.gif width=12 height=12></td><td width=557>
<a href="28.htm">Международный турнир "Компьютерная физика"</a> (В.Альминдеpов и О.Поповичева)</td></tr>
</table>

<? include("_end.htm") ?>
